project:
  type: book

book:
  title: "Introduction to Bibliographic Data Science"
  subtitle: "A training material"
  author: "Péter Király"
  date: "last-modified"
  page-navigation: true
  search: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - introduction.qmd
    - ch1.qmd
    - part: "Theoretical models"
      chapters:
        - ch2a.qmd
        - ch2b.qmd
    - part: "The data analysis workflow"
      chapters:
        - ch3a.qmd
        - ch3b.qmd
        - ch3c.qmd
        - ch3d.qmd
        - ch3e.qmd
        - ch3f.qmd
    - ch4.qmd
    - references.qmd
  appendices:
    - ap1.qmd
    - ap2.qmd
    - ap3.qmd
    - ap4.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple

execute:
  freeze: auto

